#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run this script with that shell by setting the SHELL environment
#       variable:
#           SHELL=/bin/bash ./gradlew
#
#       The "#!/bin/sh" shebang line must not be removed/changed because it
#       selects the shell actually used to run the script. However, you can set
#       the SHELL environment variable to explicitly request a shell.
#
#       When SHELL is set, the script sets the POSIXLY_CORRECT variable to disable
#       any extended non-POSIX features in bash. This is necessary to ensure the
#       script is executed in a POSIX-compliant shell to avoid emulation layer
#       issues on macOS, where the default bash is not POSIX-compliant (it has no
#       "posix" mode). Also, the "#!/bin/bash" shebang also works, but is discouraged.
#
#   (2) The script tries to detect the location of the Gradle installation
#       by reading the "distributionUrl" property from the gradle-wrapper.properties
#       file. The Gradle distribution "distributions" directory, located in the
#       user's home directory, is used as a fallback. The location can be overridden
#       by setting the GRADLE_USER_HOME environment variable.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available file descriptors if possible, if not defined, assume 0.
MAX_FD_LIMIT=$( ulimit -H -n ) || MAX_FD_LIMIT=4096
if [ -n "$__NETFLIX_TEST" ]; then
    MAX_FD_LIMIT=1
fi

# Make sure the background daemon limit is not higher than the fd limit (to kill daemons)
DAEMON_MAX_FD_LIMIT=${DAEMON_MAX_FD_LIMIT:-$MAX_FD_LIMIT}

# Check that we have a working `echo`
if [ 'X' = "X$(printf "%s\n" "$X")" ]; then
    # POSIX printf is a separate program, but in practice, it's as portable as echo.
    # Use a custom command that writes to stdout that is always a shell builtin.
    # This function is also available as an alias to avoid forking a subprocess.
    # Alpine / busybox ash doesn't support functions unless non-interactive mode is set.
    # That mode is set earlier in the script.
    echo_write() { printf "%s\n" "$*"; }
    alias echo_write='printf %s\n'
else
    echo_write() { printf %s\\n "$*"; }
    alias echo_write='printf %s\n'
fi

# Support unicode (outside of the ascii range) by using the actual shell's echo command.
# The "\$0" pattern contains the script path, which could be a non-ascii path (when the script is
# run with a custom path). The fallback will be to ignore those characters and print a path as a
# normal string (as ascii). This is acceptable because the generated string is used as a file
# path anyway. The script is shipped with the binary distribution, so it should always be ASCII.
# In a non-ascii range environment (like with Chinese locale), users may generate the wrapper
# script with a non-ascii path, but they typically want the full wrapper script to be executed
# as a string command, which works with the echo_write alias defined above.
GRADLE_ECHO="$(command -v echo 2>/dev/null)" || GRADLE_ECHO="echo_write"
"$GRADLE_ECHO" ""

# Find java

JAVA_HOME="${JAVA_HOME:-$(cygpath -u "$JAVA_HOME" 2>/dev/null)}"
if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
elif [ -x /usr/bin/java ]; then
    JAVACMD=/usr/bin/java
elif [ -x /usr/bin/java ]; then
    JAVACMD=/usr/bin/java
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$MAX_FD_LIMIT" -ne 1 ] && [ "$(ulimit -n)" -lt "$MAX_FD_LIMIT" ]; then
    ulimit -n "$MAX_FD_LIMIT" || echo_write "Warning: could not raise the maximum file descriptor limit to $MAX_FD_LIMIT"
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the classpath
#   * the sourcepath
#   * the bootstrap classpath
#   * the jar file for this application
#   * the system properties (stacked on top of the command line arguments)
#   * the java options (stacked on top of the system properties)

# Save the arguments before we tamper with them.
app_java_opts=""
args=""
for i in "$@"; do
    case "$i" in
        --)                          # end of application options
            # we could use this but we would need to keep the unprocessed arguments, but we can't
            # because the shell will mangle the arguments when it does recursive exec. This will only
            # work if the OCI runtime option to use exec is used, but we can't rely on that.
            # This won't work in the original Gradle script anyway.
            shift
            break
            ;;
        -D*)
            app_java_opts="$i ${app_java_opts}"
            shift
            ;;
        -X*)
            app_java_opts="$i ${app_java_opts}"
            shift
            ;;
        *)
            args="$i ${args}"
            shift
            ;;
    esac
done
args="$args"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx1024m" "-Xms256m"'

# Collect all arguments for the java command:
#   * default JVM options
#   * the JAVA_OPTS and GRADLE_OPTS environment variables (if set)
#   * the application options (saved earlier in $app_java_opts)
#   * the arguments

app_java_opts="$DEFAULT_JVM_OPTS $app_java_opts"

if [ -n "$JAVA_OPTS" ]; then
    app_java_opts="$JAVA_OPTS $app_java_opts"
fi

if [ -n "$GRADLE_OPTS" ]; then
    app_java_opts="$GRADLE_OPTS $app_java_opts"
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
case "$(uname)" in
    CYGWIN*|MINGW*|MSYS*)
        # For Cygwin/MSYS, convert paths to Unix/Linux style before parsing them.
        # The 'java' command understands both styles, but some Gradle APIs may not.
        # Note: when a CYGWIN path is passed, it is converted to a Windows path inside the 'java' command.
        # The 'cygpath' tool is used for conversion. Use the -u option to convert from Windows to Unix.
        # The $APP_HOME is located in Windows path style if it was set by cygpath in the first place.
        # We need to convert it to Unix path style before processing it.
        # Currently, these variables are in Windows path format. Convert them to Unix path format.
        # We also need to convert the current directory (PWD) to Unix format.
        # The PWD variable contains the fully qualified logical path of the current directory.
        # The app_dir variable is the relative path from the APP_HOME to the current directory.
        # The script resolves symlinks to the Gradle script. The resolved symlink is stored in APP_HOME.
        # It contains the absolute path. The resolved symlink is the best choice for APP_HOME.
        # This is critical for some shell commands to work correctly.
        #
        # Note: we can't use a command substitution to get the absolute path because it may fail with
        # a "command not found" error for certain shells. The fallback is to get the absolute path using
        # `pwd -P` (physical path) and resolving symlinks using `ls -ld`.
        #
        # Note: we cannot use `cd` and `pwd` to get the absolute path because we are in a sub-shell.
        # The only way to get the absolute path is to use `cd` and `pwd` in a sub-shell, which is exactly
        # what we are doing in the `resolve_symlinks` function.

        # This function emulates the behavior of `readlink -f` on systems that do not have it.
        resolve_symlinks() {
            local path="$1"
            while [ -L "$path" ]; do
                local dir="$( cd -P "$( dirname "$path" )" && pwd -P )"
                local target="$( ls -l "$path" | grep -Po '(?<=-> ).*' )"
                if echo "$target" | grep -qE '^/'; then
                    path="$target"
                else
                    path="${dir}/${target}"
                fi
            done
            echo "$( cd -P "$( dirname "$path" )" && pwd -P )/${path##*/}"
        }

        # The following lines are used to resolve symlinks in the Gradle script.
        # This script is a symlink to the actual script. This is common for Unix platforms.
        # We use the `resolve_symlinks` function to get the absolute path of the script.
        # Then we set APP_HOME to the absolute path of the script's directory.
        APP_HOME=$(cd -P "$( dirname "$0" )" && pwd -P)  # Keep APP_HOME as a physical path (resolve symlinks).
        APP_HOME=$(resolve_symlinks "$0")          # But we also need to resolve symlinks for the actual script.
        # To avoid confusion, we set APP_HOME to the physical path because it is used for the classpath
        # and other paths. It is better to use a physical path to avoid issues with symlinks.
        APP_HOME=$(cd -P "$( dirname "$APP_HOME" )" && pwd -P) # Use physical path for the application home.
        ;;

    *)
        # For Linux and other POSIX systems.
        # Convert the path to Unix style.
        APP_HOME=$(cd -P "$( dirname "$0" )" && pwd -P)
        ;;
esac

# Add the application's jar file to the classpath.
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# Function to get the value of a property from the gradle-wrapper.properties file.
get_property() {
    local prop_name="$1"
    local prop_file="$APP_HOME/gradle/wrapper/gradle-wrapper.properties"
    if [ -f "$prop_file" ]; then
        grep "^$prop_name=" "$prop_file" | cut -d'=' -f2-
    else
        echo ""
    fi
}

# Use the Gradle distribution from the wrapper.
distributionUrl=$(get_property "distributionUrl")
wrapperSha256Sum=$(get_property "distributionSha256Sum")

# Determine the Gradle user home directory.
if [ -n "$GRADLE_USER_HOME" ]; then
    GRADLE_USER_HOME="$GRADLE_USER_HOME"
elif [ -n "$HOME" ]; then
    GRADLE_USER_HOME="$HOME/.gradle"
else
    GRADLE_USER_HOME=".gradle"
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
case "$(uname)" in
    CYGWIN*|MINGW*|MSYS*)
        # Convert paths to Windows format.
        GRADLE_USER_HOME=$(cygpath -w "$GRADLE_USER_HOME" 2>/dev/null)
        ;;
esac

# The distribution directory name
distro_dir="$GRADLE_USER_HOME/wrapper/dists"
# Use the distributionUrl from the wrapper to build the distribution directory name
distro_name=$(echo "$distributionUrl" | sed 's/^.*\///' | sed 's/\.zip$//')
# The distribution directory
dist_dir="$distro_dir/$distro_name"
dist_zip="$dist_dir/$distro_name.zip"

# Ensure the distribution exists (download if not present)
if [ ! -f "$dist_zip" ]; then
    mkdir -p "$dist_dir"
    echo_write "Downloading Gradle distribution: $distributionUrl"
    if command -v curl >/dev/null 2>&1; then
        curl -L -o "$dist_zip" "$distributionUrl"
    elif command -v wget >/dev/null 2>&1; then
        wget -O "$dist_zip" "$distributionUrl"
    else
        die "Cannot download Gradle distribution: curl and wget are not available."
    fi
fi

# Verify the checksum if provided
if [ -n "$wrapperSha256Sum" ]; then
    if command -v sha256sum >/dev/null 2>&1; then
        echo_write "Verifying Gradle distribution checksum..."
        sha256sum -b "$dist_zip" | grep -q "$wrapperSha256Sum" || die "Checksum verification failed"
    elif command -v shasum >/dev/null 2>&1; then
        echo_write "Verifying Gradle distribution checksum (using shasum)..."
        shasum -a 256 -b "$dist_zip" | grep -q "$wrapperSha256Sum" || die "Checksum verification failed"
    else
        echo_write "Warning: No checksum verification tool found. Skipping checksum verification."
    fi
fi

# Unpack the distribution
if [ ! -d "$dist_dir/gradle-$distro_name" ]; then
    unzip -q "$dist_zip" -d "$dist_dir"
    mv "$dist_dir/$distro_name" "$dist_dir/gradle-$distro_name"
fi

# Set the distribution base directory
DISTRIBUTION_BASEDIR="$dist_dir/gradle-$distro_name"

# Add the distribution's bin directory to the path
PATH="$DISTRIBUTION_BASEDIR/bin:$PATH"

# Ensure the Gradle daemon is not running
if [ -f "$GRADLE_USER_HOME/daemon/$distro_name/daemon.pid" ]; then
    pid=$(cat "$GRADLE_USER_HOME/daemon/$distro_name/daemon.pid")
    if kill -0 $pid 2>/dev/null; then
        kill $pid
        echo_write "Stopped existing Gradle daemon (PID: $pid)"
    fi
fi

# Start the Gradle build
exec "$JAVACMD" $app_java_opts -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
